"""empty message

Revision ID: 18c4002acf82
Revises: 5e2861dd7d41
Create Date: 2025-03-09 11:47:57.850552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c4002acf82'
down_revision = '5e2861dd7d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_link_id', sa.String(), nullable=False))
        batch_op.drop_column('custom_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('custom_link_id')

    # ### end Alembic commands ###
