"""empty message

Revision ID: 7f1385fa1c52
Revises: 18c4002acf82
Create Date: 2025-03-09 12:43:20.815841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1385fa1c52'
down_revision = '18c4002acf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('short', sa.String(), nullable=False))
        batch_op.drop_column('custom_link_id')
        batch_op.drop_column('original_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_link', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('custom_link_id', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('short')
        batch_op.drop_column('original')

    # ### end Alembic commands ###
